# Generated by Django 2.2.7 on 2019-11-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paytm', '0003_auto_20191023_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paytmhistory',
            name='TXNID',
            field=models.CharField(max_length=50, verbose_name='TXN ID'),
        ),
    ]
